### PR TITLE
Enable code coverage

### PR DESCRIPTION
**Pull request by ahal**
This will enable code coverage reporting via `pytest-cov` and codecov.io.

### CODE REVIEW

**Comment by ahal** [comment]
Reviewing this one commit at a time might be best.

**Comment by ahal** [comment]
This is currently set up to fail a check if the PR adds any new uncovered lines. I propose we let this land for now and see how annoying / useful it is and decide whether to tweak behaviour later. I will say that when I saw I added two new uncovered lines to the `fetch.py` transforms, it prompted me to go and write some tests for that file :p.. so I think it might be a good thing overall?

**Comment by hneiva** [comment]
> ... so I think it might be a good thing overall?

+1 to that

**Comment by ahal** [comment]
Oops, failed linting.. just a sec

**Comment by ahal** [comment]
I wonder how codecov is able to compare against main given that this PR hasn't merged and we've never uploaded results from there.. Magic I guess.

**Comment by ahal** [comment]
Also worth noting that coverga.py skips the files under `src/scripts`, I guess because they aren't proper modules... I'll see if there's a way to get them included in the report as a follow-up.

**Review by gabrielBusta — APPROVED** [review]
Failing a check if the PR adds new uncovered lines could be mildly annoying but I think it will have a positive effect on the overall test coverage.

**Comment by ahal** [comment]
Yeah, I *think* Github will still display the green "Rebase and merge" button if it fails.. so it'll be easy to ignore the failure. But we can definitely adjust if it gets annoying. Thanks!

**Pull request merged**
