### PR TITLE
refactor: create new 'pytest-taskgraph' package to house test fixtures

### PR DESCRIPTION
**Pull request by ahal**
These fixtures are useful for any project that wants to test Taskgraph related transforms or scripts. By putting them in a package, we can share them to any other repos that may need them.

### CODE REVIEW

**Comment by ahal** [comment]
I tried to use uv's workspaces here, but couldn't quite get it working. Using a path instead seems to work well though.

**Review by bhearsum — APPROVED** [review]
This is very cool, thank you!!

**Comment by ahal** [comment]
There's a near 0% chance this is going to work perfectly on the first try, but I don't know how to test it all without creating a release. So I'll land and be prepared for a follow-up.

**Comment by ahal** [comment]
Here is the inevitable follow-up PR I was talking about:
https://github.com/taskcluster/taskgraph/pull/614

Possibly more to come after that

**Pull request merged**
