### PR TITLE
Strip `build-` prefix from docker image task labels

### PR DESCRIPTION
**Pull request by ahal**

### CODE REVIEW

**Comment by ahal** [comment]
There's no rush on this, just wanted to tee it up for the next time we're doing a breaking change anyway.

**Comment by jcristau** [comment]
I guess this is to align with gecko?

**Comment by ahal** [comment]
Yeah, it's blocking us consolidating the docker image logic as this prefix is hardcoded in a few places.

I guess we could make it a configuration option, but I don't like that Taskgraph defaults to `build-` as a prefix anyway, as this makes it easy to confuse them as the `build` kind if someone is parsing labels for the kind (which they shouldn't do, but happens in practice).

**Review by jcristau — APPROVED** [review]
Makes sense.

**Pull request merged**
