### PR TITLE
chore!: drop support for Python 3.6

### PR DESCRIPTION
**Pull request by ahal**
Issue: #26

### CODE REVIEW

**Comment by gabrielBusta** [comment]
We could deprecate. I don't have to move the consumers to the new Taskgraph version right away. When we bump the Taskgraph version we can also bump the Taskgraph decision image

**Comment by ahal** [comment]
Chatted with glandium, while building Firefox itself doesn't directly depend on Taskgraph, there are places where we import it at the top level. Which means we do risk breaking builds. This would only happen at vendor update time..  but still feels safer to me to just leave 3.6 alone for now. We could also refactor the build system to only import Taskgraph when it's used, but that doesn't feel worth the effort to me.

**Comment by gabrielBusta** [comment]
can we do this when this bug is closed @ahal? https://bugzilla.mozilla.org/show_bug.cgi?id=1734402

**Comment by ahal** [comment]
Superseded by #207

**Pull request closed without merging**
