### PR TITLE
revert: memoized yaml loading due to presumed thread unsafeness

### PR DESCRIPTION
**Pull request by bhearsum**

### CODE REVIEW

**Comment by bhearsum** [comment]
> We might want to also revert [40fe728](https://github.com/taskcluster/taskgraph/commit/40fe7287cc7edcba93993e7e35d17ce55cc71b3b)?

Indeed!

**Review by ahal — APPROVED** [review]
Thanks!

**Comment by ahal** [comment]
Maybe we can land this first and do a patch release before we land your other feature PRs

**Comment by bhearsum** [comment]
> Maybe we can land this first and do a patch release before we land your other feature PRs

Agreed. I'll get that rolling.

**Pull request merged**
