### PR TITLE
ci: prefer $switch over $if/else in .taskcluster.yml

### PR DESCRIPTION
**Pull request by ahal**

### CODE REVIEW

**Review by bhearsum — APPROVED** [review]
Thank you so much for doing this, it's great!

**Comment by ahal** [comment]
I'm not sure what's up with the coverage thinking I'm adding lines in `hash.py`? Maybe Heitor's patch is going to fix that..

**Comment by JohanLorenzo** [comment]
I wonder if it's just some red herring because your base commit was a month old. b18a7a7 was landed prior to https://github.com/taskcluster/taskgraph/pull/178 which did change `hash.py`: 

image

**Comment by JohanLorenzo** [comment]
By the way, I'm so glad to see these clean `$switch` statements!

**Pull request merged**
